/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ActionToolPanel.java
 *
 * Created on Jul 12, 2013, 3:27:33 PM
 */

package vms.table.panels;

import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Abner
 */
public class ActionToolPanel extends javax.swing.JPanel {

    /** Creates new form ActionToolPanel */
    public ActionToolPanel() {
        initComponents();
        initSystemProperties();
    }

    public void initSystemProperties()
    {
        JLabel label = new JLabel();
        /*JButton button1 = new JButton("");
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actiontool_icon.png")));
        button1.setText("");
        button1.setOpaque(true);*/
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actiontool_icon.png")));
        label.setText("");
        ImageIcon image;
       // la
        this.add(label);
        this.setLayout(new FlowLayout());
       //  this.setOpaque(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
