/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetupWizardDialog.java
 *
 * Created on Jun 25, 2013, 10:01:32 PM
 */

package datacollector.view.dialogs;

import datacollector.view.applications.AppView;
import datacollector.wizard.panels.SetupWizardStepP1;
import datacollector.wizard.panels.SetupWizardStepP2;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Abner
 */
public class SetupWizardDialog extends javax.swing.JDialog {

    private static final SetupWizardDialog app = new SetupWizardDialog(AppView.getInstance(), true);

    private SetupWizardStepP1 step1 = new SetupWizardStepP1();
    private SetupWizardStepP2 step2 = new SetupWizardStepP2();
    
    /** Creates new form SetupWizardDialog */
    public SetupWizardDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initWizardLayout();
        initSystemProperties();
        
    }

     /**
     *  Initialize system properties
     */
    public void initSystemProperties()
    {
        // Sets up dialog location
        AppView app = AppView.getInstance();
        Dimension viewSize = app.getSize();
        Dimension dilaogSize = this.getSize();
        this.setLocation((int)((viewSize.getWidth()/2)*0.70),(int)((viewSize.getHeight()/2) - (dilaogSize.getHeight()/2)));
    }

    public void initWizardLayout()
    {
        wizardPanel.add(step1, "1");
        wizardPanel.add(step2, "2");
    }

    public static SetupWizardDialog getInstance()
    {
        return app;
    }

    public void launch()
    {
        this.setVisible(true);
    }

    public void close()
    {
        this.setVisible(false);
    }

    public SetupWizardStepP1 getWizarStep1()
    {
        return step1;
    }

    public SetupWizardStepP2 getWizardStep2()
    {
        return step2;
    }
    
    public JPanel getWizardPanel()
    {
        return wizardPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wizardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        wizardPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 312, Short.MAX_VALUE)
                    .addComponent(wizardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 313, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 197, Short.MAX_VALUE)
                    .addComponent(wizardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 197, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel wizardPanel;
    // End of variables declaration//GEN-END:variables

}
